#!/bin/sh

#
#	$Id$
#
#	Make a components.map for a set of libraries
#
#	Neil Mayhew - 2007-07-31
#
# COM Support Library
# Copyright (C) 2007 SIL International
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# http://www.gnu.org/licenses/lgpl.html
# 

set -e

if [ $# -eq 0 ]
then
	echo "Usage: $(basename "$0") LIB ..." >&2
	exit 1
fi

OUTPUT=components.map
TEMPFILE=$(mktemp)

trap "rm -f '$OUTPUT' '$TEMPFILE'" EXIT INT QUIT TERM
exec >$OUTPUT

echo "# Autogenerated by $(basename "$0") on $(date)"
echo "#"

for LIB
do
	# Use a file, not a pipe, so that errors from RegisterServer are not lost
	RegisterServer "$LIB" >$TEMPFILE
	sed "/^[^#]/s'\$' $LIB'" $TEMPFILE
done

rm -f "$TEMPFILE"
trap EXIT
