#ifndef MESSAGEBOX_H
#define MESSAGEBOX_H
enum
{
	MB_ICONASTERISK		= 0x00000040L,
	MB_ICONEXCLAMATION	= 0x00000030L,
	MB_ICONHAND			= 0x00000010L,
	MB_ICONQUESTION		= 0x00000020L,
	MB_DEFBUTTON2		= ~0,
	MB_TASKMODAL		= ~0,

	MB_OK = 0,
	MB_OKCANCEL = 1,
	MB_ABORTRETRYIGNORE = 2,
	MB_YESNOCANCEL = 3,
	MB_YESNO = 4,
	MB_RETRYCANCEL = 5,
	MB_CANCELTRYCONTINUE = 6,
	};

int MessageBoxA(HWND, LPCTSTR, LPCTSTR, UINT);

int MessageBox(HWND hWnd, LPCTSTR lpText, LPCTSTR lpCaption, UINT uType);
#endif
