#ifndef MESSAGEBOX_H
#define MESSAGEBOX_H
enum
{
	MB_BUTTONMASK = 0x0FL,
	MB_OK = 0,
	MB_OKCANCEL = 1,
	MB_ABORTRETRYIGNORE = 2,
	MB_YESNOCANCEL = 3,
	MB_YESNO = 4,
	MB_RETRYCANCEL = 5,
	MB_CANCELTRYCONTINUE = 6,

	MB_ICONASTERISK		= 0x00000040L,
	MB_ICONEXCLAMATION	= 0x00000030L,
	MB_ICONHAND			= 0x00000010L,
	MB_ICONQUESTION		= 0x00000020L,
	MB_ICONINFORMATION	= ~MB_BUTTONMASK,
	MB_ICONSTOP			= ~MB_BUTTONMASK,

	MB_DEFBUTTON1		= ~MB_BUTTONMASK,
	MB_DEFBUTTON2		= ~MB_BUTTONMASK,
	MB_DEFBUTTON3		= ~MB_BUTTONMASK,
	MB_DEFBUTTON4		= ~MB_BUTTONMASK,
	MB_TASKMODAL		= ~MB_BUTTONMASK,
	MB_SETFOREGROUND	= ~MB_BUTTONMASK,
};

int MessageBoxA(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);

int MessageBox(HWND hWnd, LPCTSTR lpText, LPCTSTR lpCaption, UINT uType);
#endif
